# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2024 Cirrus Logic, Inc.

# Enable CS40L26 driver
CONFIG_CS40L26=y

# Enable SPI
CONFIG_SPI=y

# Enable GPIO
CONFIG_GPIO=y

# Enable logging
CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_CS40L26_LOG_LEVEL_INF=y

# Kernel options
CONFIG_MAIN_STACK_SIZE=2048
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048
